# Generated by Django 4.1.3 on 2023-02-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('location', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('age', models.CharField(default='', max_length=200)),
                ('hiredate', models.DateField(default='2023-02-27')),
                ('price', models.IntegerField(default='333')),
            ],
        ),
    ]
