# Generated by Django 4.1.3 on 2023-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_emp_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='Image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
